#!/usr/bin/env bash
#displays numbers from 1 to 100,FizzBuzz inf multiple of 3 and 5, Fizz if multiple of 3, Buzz if multiple of 5

n=0

for (( n=1;n<101;n++ ))
  do
     if (( n % 3 == 0 )) && (( n % 5 == 0 )); 
     then
	echo "FizzBuzz"
     
     elif (( n % 3 == 0 )); 
     then
        echo "Fizz"
	
     elif (( n % 5 == 0 ))
     then
        echo "Buzz"
	
     else
	echo $n

    fi
	     
done
