#!/usr/bin/env bash
#a Bash script that displays the content of the file /etc/passwd, using the while loop + IFS.

while read -r /etc/passwd

do
	   echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMAND/SHELL. $USER_ID's place is protected by the passcode $PASSWORD, more info about the user here: $USER_ID_INFO"
done
