#!/usr/bin/env bash
#Say bad luck 4 good luck 8
i=0
while [ "$i" -le 10 ]
do
        if [ "$i" = "4" ]
 then
         echo "bad luck"
        (( i++ ))
         elif [ "$i" = "8" ]
 then 
         echo "good luck"
         (( i++ ))
 else
        echo "Best School"
        (( i++ ))
 fi
done
