#!/usr/bin/env bash
#Say bad luck number in 4, 9, 17

i=1

while [ "$i" -le 20 ]
do
case $i in
4)  echo "$i\n bad luck from China"
;;
9)  echo "$i\n bad luck from Japan"
;;
17) echo "$i\n bad luck from Italy"
;;
*) echo "$i"
esac
((i++))
done
