#!/usr/bin/env bash
# script that gives you information about the file

if [[ -e "school" ]]
 then 
	echo "school file exists"
	if [[ -s "school" ]]
		then
			echo "school files is not empty"
 		else
			echo "school file is empty"
		fi
		if [[ -e && -f "school"	]]
	then
		echo "school is regular file"
	fi
		
  else
	echo "school file does not exist"

  fi
