#!/usr/bin/env bash
# script that gives you information about the file

for file in *
do
	if [ $file = "school" ]
 then 
	echo "school file exists"
	if [[ $(cat $file) = * ]]
		then
			echo "school files is not empty"
 		else
			echo "school file is empty"
		fi
		if [[ $(test - filename) = "true" ]]
	then
		echo "school is regular file"
	fi
		
  else
	echo "school file does not exist"

  fi
done
