#!/usr/bin/env bash
# Does several things
echo '$$' > /var/run/myscript.pid
while :
do
	echo "To infinity and beyond"
	sleep 2
trap "echo 'I hate the kill command'" 15
trap "echo 'Y U no love me?!'" 2 
done
