#!/bin/env bash
# Does several things

echo '$$' > /var/run/myscript.pid
while :
do
	echo "To infinity and beyond"
	sleep 2

trap "echo I hate the kill command; exit" 15

trap "echo Y U no love me?!; exit" 2

trap "rm /var/run/myscript.pid; exit" 15||3

done
