#!/usr/bin/env bash
# displays to infinity and beyond indefinitely and say i am invincible when revicing a sigterm signal
while :
do
	echo "To infinity and beyond"
	sleep 2
trap echo I am invincible!!! 15 
done
